# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

plugins: 
  - jekyll-paginate
  
# Setup
title:            Peter
tagline:          '#FullStackDeveloper #AppliedAICoder #Innovator #Blockchain'
description:      '#FullStackDeveloper #AppliedAICoder #Innovator #Blockchain'
url:              http://petershodeinde.ai
baseurl:          /

author:
  name:           'Peter Shodeinde'
  url:            https://twitter.com/petershodeinde

paginate:         5

# Custom vars
version:          3.4.0

github:
  repo:           https://github.com/dimonge/brand
